
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("CoffeeApp_Droid.Resource", IsApplication=true)>]
    do ()

namespace CoffeeApp_Droid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException33cea99447b04053852ac6558d158bda of obj
    exception ReturnNoneException33cea99447b04053852ac6558d158bda
    [<AutoOpen>]
    module FuncConvertFinalOverload33cea99447b04053852ac6558d158bda =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                ()


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member Icon = 2130837504
            
            // aapt resource value: 0x7f020001
            static member monoandroidsplash = 2130837505
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060003
            static member buttonMin = 2131099651
            
            // aapt resource value: 0x7f060002
            static member buttonPlus = 2131099650
            
            // aapt resource value: 0x7f060005
            static member drinkItemListView = 2131099653
            
            // aapt resource value: 0x7f060000
            static member drinkRow = 2131099648
            
            // aapt resource value: 0x7f060006
            static member resetButton = 2131099654
            
            // aapt resource value: 0x7f060004
            static member textViewProductCount = 2131099652
            
            // aapt resource value: 0x7f060001
            static member textViewProductName = 2131099649
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member DrinkRowView = 2130903040
            
            // aapt resource value: 0x7f030001
            static member Main = 2130903041
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040002
            static member app_name = 2130968578
            
            // aapt resource value: 0x7f040001
            static member hello = 2130968577
            
            // aapt resource value: 0x7f040000
            static member library_name = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Style () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050000
            static member Mono_Android_Theme_Splash = 2131034112
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

